### ISSUE TITLE
Starts on system boot

### ISSUE THREAD

**Issue by boredsquirrel** [tonywalker1/silverblue-update#2]
This is a total nogo, I dont know the reason but when I start my system, among all other apps this script also starts, with a flatpak update (slowing it down already quite a bit) and then an rpm-ostree update, making it sluggish as hell.

The performance effect of that is extreme. Can you set the timer to only go off at 20pm or something?

**Comment by tonywalker1** [comment]
A perfectly reasonable suggestion and PR. However, would you mind making a change? Allow me to explain...

Issue #1 asked about setting the update interval. I can see someone wanting a different start time. I addressed the request in issue #1 with instructions to change the interval. Maybe the solution here is better instructions from me (or both of us). Instead of removing OnBootSec, we should leave it for those who want their update to run on boot. Would you modify your PR so that both options are present but one commented out? Then one or both of us edit README.md so that the first step of installation is to customize the unit file and then run the installer script. Does that sound reasonable? Thanks for contributing!

**Comment by tonywalker1** [comment]
Oh, yes. Add yourself to the copyright.

**Comment by tonywalker1** [comment]
I just pushed a new README.md.
